# Generated by Django 3.0.8 on 2021-01-21 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceId', models.PositiveIntegerField()),
                ('BillingEntity', models.CharField(max_length=16)),
                ('BillType', models.CharField(max_length=16)),
                ('PayerAccountId', models.PositiveIntegerField()),
                ('BillingPeriodStartDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=512)),
                ('cacheEngine', models.CharField(blank=True, max_length=512, null=True)),
                ('databaseEdition', models.CharField(blank=True, max_length=512, null=True)),
                ('databaseEngine', models.CharField(blank=True, max_length=512, null=True)),
                ('deploymentOption', models.CharField(blank=True, max_length=512, null=True)),
                ('instanceType', models.CharField(blank=True, max_length=512, null=True)),
                ('instanceTypeFamily', models.CharField(blank=True, max_length=512, null=True)),
                ('licenseModel', models.CharField(blank=True, max_length=512, null=True)),
                ('location', models.CharField(blank=True, max_length=512, null=True)),
                ('operatingSystem', models.CharField(blank=True, max_length=512, null=True)),
                ('region', models.CharField(blank=True, max_length=512, null=True)),
                ('tenancy', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UsageAccountId', models.PositiveIntegerField(db_index=True)),
                ('LineItemType', models.CharField(max_length=28)),
                ('UsageStartDate', models.DateTimeField()),
                ('UsageEndDate', models.DateTimeField()),
                ('UsageType', models.CharField(max_length=512)),
                ('Operation', models.CharField(blank=True, max_length=512, null=True)),
                ('AvailabilityZone', models.CharField(blank=True, max_length=512, null=True)),
                ('ResourceId', models.CharField(blank=True, max_length=512, null=True)),
                ('UsageAmount', models.FloatField()),
                ('NormalizationFactor', models.FloatField(blank=True, null=True)),
                ('NormalizedUsageAmount', models.FloatField(blank=True, null=True)),
                ('UnblendedRate', models.FloatField(blank=True, null=True)),
                ('UnblendedCost', models.FloatField()),
                ('LineItemDescription', models.CharField(max_length=512)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiV1.Bill')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiV1.Product')),
            ],
        ),
    ]
